// <auto-generated />
namespace BITCollege_KS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class remainingmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remainingmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201809241821426_remainingmodels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
